# Config file for automatic testing at travis-ci.org
sudo: required
language: python
dist: xenial
python: 3.7

install:
  - pip install tox-travis
script:
  - tox -p 5
  - sonar-scanner -Dsonar.projectKey=symonk_validate  -Dsonar.organization=symonk-github
branches:
  only:
    - master
git:
  depth: 99999


cache:
  directories:
    - "$HOME/.sonar/cache"
addons:
  apt:
    update: true
  sonarcloud:
    organization: symonk-github
